### ISSUE TITLE
导入from scipy.misc import imread出现错误，建议进行备注

### ISSUE THREAD

**Issue by tianshanzhilong** [Stansec233/JD-spider#1]
在此处查到的解决办法，https://www.jianshu.com/p/303733788362
因为scipy库中的imread要被弃用也就是不能用了，这时需要改成这样`from imageio import imread

目前使用的是python3.8版本

**Comment by Stansec233** [comment]
喔喔，忘记标注是3.6版本写的了，感谢反馈！
